name: Training Unit and Integration Tests for agentops
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'agentops/**'
      - '.github/workflows/agentops-run-tests.yml'

defaults:
  run:
    working-directory: ./agentops/

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
  

concurrency: agentops-training-integration-test-staging

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_test:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.278.0
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        run: |
          databricks bundle validate -t test
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        run: |
          databricks bundle deploy -t test
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t test
